version: '3.9'

services:
  content-service-api:
    build: .
    restart: unless-stopped
    container_name: content_service
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8000
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}"
    ports:
      - 8002:8000
    links:
      - content-service-postgres

  content-service-postgres:
    image: "postgres:latest"
    restart: unless-stopped
    container_name: content_service_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432


